[package]
name = "rivet"
version = "0.1.0"
authors = ["maciejkula <maciej.kula@gmail.com>"]

[dependencies]
reqwest = "0.6.2"
zip = "0.2.3"

app_dirs = "1.1.1"

serde = "1.0"
serde_derive = "1.0"

serde_json = "1.0"
csv = "1.0.0-beta.3"

itertools = "0.6.0"

rand = "0.3.15"